name: Nalu-Wind-CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: GCC-8.3.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: docker build -t nalu-wind .
  cuda-build:
    name: CUDA-11.1/GCC-8.3.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: docker build -f ./docker/Dockerfile.cuda -t nalu-wind .
